services:
  master1:
    build: 
      context: .
      target: hadoop
    hostname: master1
    container_name: master1
    ports:
      - "9180:8088"
      - "9885:9870"
    networks:
      - hd_net
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn1 && jps | grep -q QuorumPeerMain"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - namenode1:/usr/local/hadoop/hdfs/namenode
      - journalnode1:/usr/local/hadoop/hdfs/journals
      - zookeeper1:/usr/local/zookeeper/data
  master2:
    build: 
      context: .
      target: hadoop
    hostname: master2
    container_name: master2
    ports:
      - "9280:8088"
      - "9886:9870"
    networks:
      - hd_net
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -q QuorumPeerMain"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - namenode2:/usr/local/hadoop/hdfs/namenode
      - journalnode2:/usr/local/hadoop/hdfs/journals
      - zookeeper2:/usr/local/zookeeper/data
  master3:
    build: 
      context: .
      target: hadoop
    hostname: master3
    container_name: master3 
    ports:
      - "9380:8088"
      - "9887:9870"
    networks:
      - hd_net
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -q QuorumPeerMain"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - namenode3:/usr/local/hadoop/hdfs/namenode
      - journalnode3:/usr/local/hadoop/hdfs/journals
      - zookeeper3:/usr/local/zookeeper/data
  worker: 
    build: 
      context: .
      target: hadoop
    hostname: worker
    container_name: worker
    depends_on:
      master1: 
        condition: service_healthy
    networks:
      - hd_net
    volumes:
      - datanode1:/usr/local/hadoop/hdfs/datanode

  hmaster1:
    build: 
      context: .
      target: hbase
    hostname: hbasem1
    container_name: hmaster1
    depends_on:
      master1: 
        condition: service_healthy
      master2: 
        condition: service_healthy
      master3:
        condition: service_healthy 
    ports:
      - "16010:16010"
    networks:
      - hd_net
   
  hmaster2:
    build: 
      context: .
      target: hbase
    hostname: hbasem2
    container_name: hmaster2
    depends_on:
      master1: 
        condition: service_healthy
      master2: 
        condition: service_healthy
      master3:
        condition: service_healthy 
    ports:
      - "16011:16010"
    networks:
      - hd_net

  regionserver1:
    build:
      context: .
      target: hbase
    hostname: regionserver1
    container_name: regionserver1
    depends_on:
      master1: 
        condition: service_healthy
      master2: 
        condition: service_healthy
      master3:
        condition: service_healthy 
    ports:
      - "16030:16030"
    networks:
      - hd_net

  regionserver2:
    build:
      context: .
      target: hbase
    hostname: regionserver2
    container_name: regionserver2
    depends_on:
      master1: 
        condition: service_healthy
      master2: 
        condition: service_healthy
      master3:
        condition: service_healthy 
    ports:
      - "16031:16030"
    networks:
      - hd_net
    
volumes:
  namenode1:
  namenode2:
  namenode3:
  journalnode1:
  journalnode2:
  journalnode3:
  datanode1:
  zookeeper1:
  zookeeper2:
  zookeeper3:
    
networks:
  hd_net:


